language: elixir
elixir:
  - 1.4
otp_release:
  - 19.0
sudo: false
script:
  - mix test
  - mix credo

  - MIX_ENV=test mix clean
  - UUID=resource_owners mix test

  - MIX_ENV=test mix clean
  - UUID=all mix test
