language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
env:
  - MIX_ENV=test
sudo: false
matrix:
  include:
    - elixir: 1.8
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 21.0
      env: UUID=true
script:
  - mix test
after_script:
  - mix credo
